import type { NextPage } from 'next'
import { useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useDispatch } from 'react-redux';
import { About, Footer, Header, Experience, Poster, Resume, Skill, Certificate } from '../src/components'
import { changeActive } from '../src/redux/reducers/active';

const Home: NextPage = () => {
  const dispatch = useDispatch()
  useEffect(() => {
    const handleScroll = () => {
      const sections = document.querySelectorAll('section[id]');
      const currentSection = Array.from(sections).find((section) => {
        const rect = section.getBoundingClientRect();
        return rect.top <= 0 && rect.bottom >= 0;
      });
      if (currentSection) {
        dispatch(changeActive(`#${currentSection.id}`))
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, [dispatch]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Tran Huu Vinh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Poster />
        <About />
        <Resume />
        <Skill />
        <Certificate />
        <Experience />
        <Footer />
      </main>
    </div>
  )
}

export default Home

