import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import AOS from "aos";
import "aos/dist/aos.css";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import {
  About,
  Footer,
  Header,
  Experience,
  Poster,
  Resume,
  Skill,
  Certificate,
} from "../src/components";
import { changeActive } from "../src/redux/reducers/active";
import { motion, useScroll } from "framer-motion";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { scrollYProgress } = useScroll();

  useEffect(() => {
    AOS.init();
  }, []);

  useEffect(() => {
    const handleScroll = () => {
      const sections = document.querySelectorAll("section[id]");
      const currentSection = Array.from(sections).find((section) => {
        const rect = section.getBoundingClientRect();
        return rect.top <= 0 && rect.bottom >= 0;
      });
      if (currentSection) {
        dispatch(changeActive(`#${currentSection.id}`));
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [dispatch]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Tran Huu Vinh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <motion.div
          className="progress-bar"
          style={{ scaleX: scrollYProgress }}
        /> */}
        <Header />
        <Poster />
        <About />
        <Resume />
        <Skill />
        <Certificate />
        <Experience />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
