import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { About, Footer, Header, Portfolio, Poster, Resume, Skill } from '../src/components'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tran Huu Vinh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Poster />
        <About />
        <Skill />
        <Resume />
        <Portfolio />
        <Footer />
      </main>
    </div>
  )
}

export default Home
